# Generated by Django 5.2.8 on 2025-12-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizMania', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='duration',
            field=models.IntegerField(default=5),
        ),
    ]
