# Generated by Django 5.2.8 on 2025-12-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizMania', '0002_question_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztaker',
            name='alias',
            field=models.CharField(default='Guest', max_length=255),
        ),
    ]
