# Generated by Django 5.2.8 on 2025-12-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizMania', '0004_quizhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
